/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labpractico6;

import java.awt.Graphics;
import java.awt.Image;
import java.util.TreeMap;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author patri
 */
public class DeTodoSa extends javax.swing.JFrame {
   
    /**
     * Creates new form DeTodoSa
     */
    static TreeMap<Integer,Producto> mercaderia;
    public DeTodoSa() {
        initComponents();
        mercaderia= new TreeMap<Integer,Producto>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        ImageIcon icono = new ImageIcon(getClass().getResource("/Resource/fondo1.jpg"));
        Image fondo1 = icono.getImage();
        escritorio = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g) {
                g.drawImage(fondo1, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministracion = new javax.swing.JMenu();
        menuModificacion = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        jMnombre = new javax.swing.JMenuItem();
        jMprecio = new javax.swing.JMenuItem();
        jMrubro = new javax.swing.JMenuItem();
        menuOut = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        menuAdministracion.setText("Administracion");

        menuModificacion.setText("Agregar/Eliminar/Modificar");
        menuModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificacionActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuModificacion);

        jMenuBar1.add(menuAdministracion);

        menuConsulta.setText("Consulta");

        jMnombre.setText("Por nombre");
        jMnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnombreActionPerformed(evt);
            }
        });
        menuConsulta.add(jMnombre);

        jMprecio.setText("Por precio");
        jMprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMprecioActionPerformed(evt);
            }
        });
        menuConsulta.add(jMprecio);

        jMrubro.setText("Por rubro");
        jMrubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMrubroActionPerformed(evt);
            }
        });
        menuConsulta.add(jMrubro);

        jMenuBar1.add(menuConsulta);

        menuOut.setText("Salir");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuOut.add(menuSalir);

        jMenuBar1.add(menuOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void menuModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificacionActionPerformed
        GestionDeProductos gestion = new GestionDeProductos();
        escritorio.add(gestion);
        gestion.setVisible(true);
        centrarInternalFrame(gestion);
    }//GEN-LAST:event_menuModificacionActionPerformed

    private void jMprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMprecioActionPerformed
        ConsultaPorPrecio consultaPorPrecio = new ConsultaPorPrecio();
        escritorio.add(consultaPorPrecio);
        consultaPorPrecio.setVisible(true);
        centrarInternalFrame(consultaPorPrecio);
    }//GEN-LAST:event_jMprecioActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que querés Salir?",
                "Confirmar Salida",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            
            this.dispose();
            
            
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    private void jMnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnombreActionPerformed
        VentanaPorNombre vistaNombre = new VentanaPorNombre();
        escritorio.add(vistaNombre);
        vistaNombre.setVisible(true);
        centrarInternalFrame(vistaNombre);
    }//GEN-LAST:event_jMnombreActionPerformed

    private void jMrubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMrubroActionPerformed
        ConsultaPorRubro vistaRubro = new ConsultaPorRubro();
        escritorio.add(vistaRubro);
        vistaRubro.setVisible(true);
        centrarInternalFrame(vistaRubro);
    }//GEN-LAST:event_jMrubroActionPerformed

    private void centrarInternalFrame(JInternalFrame internalFrame) {
        // Centrar el internal frame en el escritorio
        int x = (escritorio.getWidth() - internalFrame.getWidth()) / 2;
        int y = (escritorio.getHeight() - internalFrame.getHeight()) / 2;
        internalFrame.setLocation(x, y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodoSa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodoSa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodoSa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodoSa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodoSa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMnombre;
    private javax.swing.JMenuItem jMprecio;
    private javax.swing.JMenuItem jMrubro;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuModificacion;
    private javax.swing.JMenu menuOut;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
